[project]
name = "code-review-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "github-copilot-sdk[telemetry]>=1.0.9",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.0.0",
    "ruff>=0.16.3",
]
